
import com.mysql.jdbc.Statement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author DANE-PC
 */
public class frmTesti extends javax.swing.JFrame {

    private DefaultTableModel model;
    

    /**
     * Creates new form frmTamu
     */
    public frmTesti() {
        initComponents();
        model = new DefaultTableModel();
        tblTestimoni.setModel(model);
        model.addColumn("Nama");
        model.addColumn("Email");
        model.addColumn("Komentar"); 
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        mainPanel = new javax.swing.JPanel();
        panelAtas1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtNama = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtKomentar = new javax.swing.JTextArea();
        btnSend2 = new javax.swing.JButton();
        TblDetail = new javax.swing.JScrollPane();
        tblTestimoni = new javax.swing.JTable();
        btnSend1 = new javax.swing.JButton();
        btnHome = new javax.swing.JButton();

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        mainPanel.setBackground(new java.awt.Color(255, 255, 255));
        mainPanel.setPreferredSize(new java.awt.Dimension(570, 450));
        mainPanel.setLayout(null);

        panelAtas1.setBackground(new java.awt.Color(3, 169, 244));
        panelAtas1.setMinimumSize(new java.awt.Dimension(327, 69));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Buku Tamu");

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Wisata Riau");

        javax.swing.GroupLayout panelAtas1Layout = new javax.swing.GroupLayout(panelAtas1);
        panelAtas1.setLayout(panelAtas1Layout);
        panelAtas1Layout.setHorizontalGroup(
            panelAtas1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAtas1Layout.createSequentialGroup()
                .addGroup(panelAtas1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelAtas1Layout.createSequentialGroup()
                        .addGap(370, 370, 370)
                        .addComponent(jLabel7))
                    .addGroup(panelAtas1Layout.createSequentialGroup()
                        .addGap(391, 391, 391)
                        .addComponent(jLabel8)))
                .addContainerGap(390, Short.MAX_VALUE))
        );
        panelAtas1Layout.setVerticalGroup(
            panelAtas1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAtas1Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE))
        );

        mainPanel.add(panelAtas1);
        panelAtas1.setBounds(0, 0, 880, 70);

        jLabel1.setText("Nama");
        mainPanel.add(jLabel1);
        jLabel1.setBounds(50, 130, 50, 14);

        jLabel9.setText("Email");
        mainPanel.add(jLabel9);
        jLabel9.setBounds(50, 170, 34, 14);

        jLabel10.setText("Komentar");
        mainPanel.add(jLabel10);
        jLabel10.setBounds(50, 210, 60, 14);

        txtNama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNamaActionPerformed(evt);
            }
        });
        mainPanel.add(txtNama);
        txtNama.setBounds(110, 120, 260, 30);

        txtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailActionPerformed(evt);
            }
        });
        mainPanel.add(txtEmail);
        txtEmail.setBounds(110, 160, 260, 30);

        txtKomentar.setColumns(20);
        txtKomentar.setRows(5);
        jScrollPane1.setViewportView(txtKomentar);

        mainPanel.add(jScrollPane1);
        jScrollPane1.setBounds(110, 200, 260, 130);

        btnSend2.setText("View Comment");
        btnSend2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSend2ActionPerformed(evt);
            }
        });
        mainPanel.add(btnSend2);
        btnSend2.setBounds(520, 360, 140, 23);

        tblTestimoni.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        TblDetail.setViewportView(tblTestimoni);

        mainPanel.add(TblDetail);
        TblDetail.setBounds(420, 120, 320, 230);

        btnSend1.setText("Send");
        btnSend1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSend1ActionPerformed(evt);
            }
        });
        mainPanel.add(btnSend1);
        btnSend1.setBounds(110, 340, 57, 23);

        btnHome.setText("Home");
        btnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomeActionPerformed(evt);
            }
        });
        mainPanel.add(btnHome);
        btnHome.setBounds(30, 80, 80, 23);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 876, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 488, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailActionPerformed

    private void txtNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNamaActionPerformed

    private void btnSend2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSend2ActionPerformed
        DefaultTableModel tableTesti = new DefaultTableModel();
        tableTesti.addColumn("Nama");
        tableTesti.addColumn("Email");
        tableTesti.addColumn("Komentar");
        tblTestimoni.setModel(tableTesti);
        
        try {
            Statement st = (Statement) koneksi.getConnection().createStatement();
            ResultSet rs = st.executeQuery("select * from testi");
            while (rs.next()) {
                tableTesti.addRow(new Object[]{
                    rs.getString("nama"),
                    rs.getString("email"),
                    rs.getString("komen")
                });
            }
        } catch (Exception e) {

        }
    }//GEN-LAST:event_btnSend2ActionPerformed

    private void btnSend1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSend1ActionPerformed
        String Nama = txtNama.getText();
        String Email = txtEmail.getText();
        String Komentar = txtKomentar.getText();
        
        try {
            Statement st = (Statement) koneksi.getConnection().createStatement();
            st.executeUpdate("Insert into testi(nama,email,komen)" + "values('" + Nama + "','" + Email + "','" + Komentar + "');");
            JOptionPane.showMessageDialog(null, "Terima Kasih!");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Gagal input data...");
        }
    }//GEN-LAST:event_btnSend1ActionPerformed

    private void btnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeActionPerformed
       dispose();
        main a = new main();
        a.setVisible(true);
    }//GEN-LAST:event_btnHomeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmTesti.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmTesti.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmTesti.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmTesti.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmTesti().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane TblDetail;
    private javax.swing.JButton btnHome;
    private javax.swing.JButton btnSend1;
    private javax.swing.JButton btnSend2;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JPanel panelAtas1;
    private javax.swing.JTable tblTestimoni;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextArea txtKomentar;
    private javax.swing.JTextField txtNama;
    // End of variables declaration//GEN-END:variables
}
